# Puerto del servidor
server.port=8080

# Cadena de conexión para MongoDB (Atlas o Local)
# Para usar MongoDB Atlas, reemplaza la siguiente URI con tu cadena de conexión de Atlas:
# Ejemplo Atlas: spring.data.mongodb.uri=mongodb+srv://<usuario>:<password>@<cluster>.mongodb.net/?retryWrites=true&w=majority
# Por defecto se configura una URI local para pruebas de desarrollo rápido:
spring.data.mongodb.uri=mongodb+srv://admin:<PASSWORD>@cluster0.cgxyayd.mongodb.net/?appName=Cluster0
# spring.data.mongodb.uri=mongodb://localhost:27017

# Nombre de la base de datos requerido para este proyecto
spring.data.mongodb.database=tutorias_Spaghetti
