spring.application.name=tutorias
spring.data.mongodb.uri=mongodb+srv://admin:EYRWyZo4r5dzWIKc@cluster0.cgxyayd.mongodb.net/?tutorias_Capas=Cluster0
server.port=8080

# Logging configurations
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.tutorias=INFO

# SpringDoc configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
