spring.application.name=tutorias-ddd
#spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/tutorias_ddd}
spring.data.mongodb.uri=mongodb+srv://admin:EYRWyZo4r5dzWIKc@cluster0.cgxyayd.mongodb.net/tutorias_ddd?appName=Cluster0

server.port=8080
